stages:
  train:
    cmd: python src/pet_care_model.py
    deps:
    - src
    - ds
    - params.yaml

params:
- params.yaml
artifacts:
  model:
    path: model.keras
    type: model
    desc: model
plots:
- dvclive/plots/metrics:
    x: step
